### ISSUE TITLE
undefined method `xapit'

### ISSUE THREAD

**Issue by elmatou** [ryanb/xapit#48]
Hi,
working with rails 2.3.8 and Activerecord, I had some trouble to setup Xapit.
After including the gem, running the generator, and setting up my class.
    Rails::Initializer.run do |config|
    ...
     config.gem 'xapit'

```
Xapit.setup(:database_path => "#{Rails.root}/db/xapian")

class Depense < ActiveRecord::Base
...
 xapit do |x|
   x.text :motif, :categorie
   x.field :imputable_type, :imputable_id
   x.sortable :date, :motif
 end
```

I got a undefined method error while running:

> rake :xapit:index
>    rake aborted!
>    undefined method `xapit' for #Class:0xb6f2a650
>   ........
> It seem's the Membership module wasn't included in Activerecord::Base as documented.
> of  course My workaround is :
>     include Xapit::Membership
> in Activerecord::Base explicitly setup.

clearly
    if defined? ActiveRecord
      ActiveRecord::Base.class_eval do
        include Xapit::Membership
      end
    end
doesn't work on my system...
